#!/usr/bin/env julia
# setup.jl — detect embedding backend and Modelica library, generate config.toml.
# Safe to re-run: asks before overwriting an existing config.toml.
import Dates

const PROJECT_DIR = dirname(abspath(@__FILE__))
const CONFIG_PATH = joinpath(PROJECT_DIR, "config.toml")

println("=" ^ 60)
println("ModelicaRag — setup")
println("=" ^ 60)
println()

# ── detect backends ────────────────────────────────────────────────────────

github_token = get(ENV, "GITHUB_TOKEN", "")

ollama_bin = Sys.which("ollama")
has_ollama = ollama_bin !== nothing

llama_candidates = [
    expanduser("~/llama.cpp/build/bin/llama-server"),
    "/usr/local/bin/llama-server",
    "/usr/bin/llama-server",
]
llama_exe_idx = findfirst(isfile, llama_candidates)
llama_exe     = llama_exe_idx !== nothing ? llama_candidates[llama_exe_idx] : ""

function find_embed_model()
    for d in [expanduser("~/llama.cpp/models")]
        isdir(d) || continue
        candidates = filter(f -> endswith(f, ".gguf") && occursin("embed", lowercase(f)), readdir(d))
        isempty(candidates) || return joinpath(d, first(candidates))
    end
    return ""
end
gguf_model = find_embed_model()

# ── report detections ──────────────────────────────────────────────────────

println("Available embedding backends:")
!isempty(github_token) && println("  [1] github_models  (GITHUB_TOKEN detected — free, no local server needed)")
has_ollama              && println("  [2] ollama         (Ollama found at $ollama_bin)")
!isempty(llama_exe)     && println("  [3] llama          (llama-server found at $llama_exe)")
println()

backend = if !isempty(github_token)
    "github_models"
elseif has_ollama
    "ollama"
elseif !isempty(llama_exe)
    "llama"
else
    println("No embedding backend detected.")
    println("Options:")
    println("  - Install Ollama (https://ollama.com) and run: ollama pull nomic-embed-text")
    println("  - Set GITHUB_TOKEN to use the GitHub Models free API")
    println("  - Build llama-server from llama.cpp")
    println()
    "ollama"
end

print("Embedding backend [$backend]: ")
answer = strip(readline())
backend = isempty(answer) ? backend : answer

embed_url   = "http://localhost:8080"
embed_model = "text-embedding-3-small"

if backend == "ollama"
    embed_url   = "http://localhost:11434"
    embed_model = "nomic-embed-text"
elseif backend == "github_models"
    print("GitHub embedding model [text-embedding-3-small]: ")
    m = strip(readline())
    embed_model = isempty(m) ? "text-embedding-3-small" : m
end

# ── find Modelica Standard Library ────────────────────────────────────────

function find_modelica_library()
    for root in ["/usr/share/openmodelica/libraries", "/usr/lib/omlibrary",
                 "/usr/local/lib/omlibrary", expanduser("~/.openmodelica/libraries")]
        isdir(root) || continue
        for entry in readdir(root)
            startswith(entry, "Modelica") && isdir(joinpath(root, entry)) && return joinpath(root, entry)
        end
    end
    return ""
end

mo_lib = find_modelica_library()
println("\nModelica library: $(isempty(mo_lib) ? "not found" : mo_lib)")

print("Modelica library root [$(isempty(mo_lib) ? "/path/to/Modelica/library" : mo_lib)]: ")
answer = strip(readline())
mo_lib = isempty(answer) ? mo_lib : answer

# ── check for existing config ──────────────────────────────────────────────

if isfile(CONFIG_PATH)
    print("\nconfig.toml already exists. Overwrite? [y/N]: ")
    answer = lowercase(strip(readline()))
    answer in ("y", "yes") || (println("Aborted."); exit(0))
end

# ── write config.toml ─────────────────────────────────────────────────────

mkpath(joinpath(PROJECT_DIR, "data"))

open(CONFIG_PATH, "w") do io
    println(io, "# Generated by setup.jl on $(Dates.today())")
    println(io, "# Run `julia setup.jl` again to regenerate.\n")
    println(io, "[embeddings]")
    println(io, "backend    = \"$backend\"")
    if backend == "ollama"
        println(io, "url        = \"$embed_url\"")
        println(io, "model      = \"$embed_model\"")
    elseif backend == "github_models"
        println(io, "model      = \"$embed_model\"")
        println(io, "# token is read from the GITHUB_TOKEN environment variable.")
    else
        println(io, "url        = \"$embed_url\"")
    end
    println(io, "batch_size = 32\n")
    println(io, "[server]")
    println(io, "llama_server = \"$(isempty(llama_exe) ? "~/llama.cpp/build/bin/llama-server" : llama_exe)\"")
    println(io, "model_path   = \"$(isempty(gguf_model) ? "~/llama.cpp/models/Qwen3-Embedding-8B-Q8_0.gguf" : gguf_model)\"\n")
    println(io, "[store]")
    println(io, "path = \"$(joinpath(PROJECT_DIR, "data", "index.db"))\"\n")
    println(io, "[codebase]")
    if isempty(mo_lib) || mo_lib == "/path/to/Modelica/library"
        println(io, "# TODO: set this to your Modelica library path")
        println(io, "root       = \"/path/to/Modelica/library\"")
    else
        println(io, "root       = \"$mo_lib\"")
    end
    println(io, "extensions = [\".mo\"]")
end

println("\nWritten: $CONFIG_PATH")
(isempty(mo_lib) || mo_lib == "/path/to/Modelica/library") &&
    println("\n  ACTION REQUIRED: edit config.toml and set [codebase] root")
println()
println("Next steps:")
if backend == "github_models"
    println("  1. export GITHUB_TOKEN=<your token>")
    println("  2. julia -e 'push!(LOAD_PATH, \".\"); using ModelicaRag; ModelicaRag.main([\"index\"])'")
elseif backend == "ollama"
    println("  1. ollama pull $embed_model")
    println("  2. julia -e 'push!(LOAD_PATH, \".\"); using ModelicaRag; ModelicaRag.main([\"index\"])'")
else
    println("  julia -e 'push!(LOAD_PATH, \".\"); using ModelicaRag; ModelicaRag.main([\"index\"])'")
end
